### ISSUE TITLE
Error when loading texture image

### ISSUE THREAD

**Issue by Oneof300** [JirkaDellOro/Prima#48]
DOMException: Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded.
    at EventTarget.injectCoatTextured (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:694:26)
    at Function.draw (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:1468:22)
    at drawNode (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:7807:35)
    at Function.drawGraphRecursive (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:7789:17)
    at Function.drawGraph (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:7771:31)
    at EventTarget.draw (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:4307:37)
    at EventTarget.update (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/L14_DoomFace/Main.js:26:22)
    at EventTarget.dispatchEvent (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:222:26)
    at Function.loop (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:8384:35)
    at Function.loopTime (file:///C:/Users/Matthias/Dropbox/HFU/PRIMA/PRIMA_Repos/S20/FudgeCore/FudgeCore.js:8394:26)

**Comment by JirkaDellOro** [comment]
Ist das eine Frage?

**Comment by Oneof300** [comment]
Ja, ich habe wie meine Kommilitonen eine Textur geladen, jedoch ist dieser Fehler aufgetaucht. Was kann man machen um diesen Fehler zu beheben?

**Comment by JirkaDellOro** [comment]
Cross-Origin deutet darauf hin, dass der Browser nicht mitspielen will. Startest Du mit einem lokalen Server?
